### ISSUE TITLE
"'NumberHandler' object has no attribute 'arrayByteCount'" Error 

### ISSUE THREAD

**Issue by lion117** [jcteng/opengl-tutorial#2]
**Describe the bug**
When I run those demos , only tu1 and tu2 could work. the left demo report error . 

**Expected behavior**
here is my error report 
```
Traceback (most recent call last):
  File "src\wrapper.pyx", line 66, in OpenGL_accelerate.wrapper.CArgCalculatorElement.c_call
  File "D:\Anaconda3\lib\site-packages\OpenGL\GL\images.py", line 499, in __call__
    return arraydatatype.ArrayDatatype.arrayByteCount(arg)
  File "src\arraydatatype.pyx", line 257, in OpenGL_accelerate.arraydatatype.ArrayDatatype.arrayByteCount
AttributeError: ("'NumberHandler' object has no attribute 'arrayByteCount'", 6, <OpenGL.platform.baseplatform.glCompressedTexImage2D object at 0x000000000BD590D8>)
```

**Desktop (please complete the following information):**
 - OS:  windows 7 sp1
 - python37

**Comment by jcteng** [comment]
version problem, this demo only works on python27x ,do not use python3x

**Comment by chaojijun52** [comment]
I've got these demos work on python2.7 in linux except tu_04_1_ue4model.py. To get rid of the issue asked in this topic, you need to remove the parameter "size" from the method "glCompressedTexImage2D":
`glCompressedTexImage2D(GL_TEXTURE_2D, level, format, width, height,
            0, ddsbuffer[offset:offset+size])
 #glCompressedTexImage2D(GL_TEXTURE_2D, level, format, width, height,
 #                       0, size, ddsbuffer[offset:offset + size])`

Then you got it run.
